name: Android Build

on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
      platform:
        required: true
      build_type:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Download ZIP from backend
      - name: Download project
        run: |
          curl -L https://humidly-unsymbolic-jacquie.ngrok-free.dev/build/${{ inputs.build_id }}/download -o project.zip

      # 2. Unzip
      - name: Extract project
        run: unzip project.zip -d project

      - name: Move into project
        run: cd project && ls

      # 3. Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 4. Install deps
      - name: Install dependencies
        working-directory: project
        run: npm install

      # 5. Install Expo
      - run: npm install -g expo-cli

      # 6. Prebuild
      - name: Expo prebuild
        working-directory: project
        run: npx expo prebuild --platform android --no-install

      # 7. Setup Java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 8. Build APK
      - name: Build APK
        working-directory: project/android
        run: ./gradlew assembleRelease

      # 9. Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: project/android/app/build/outputs/apk/release/app-release.apk

      # 10. Notify backend
      - name: Notify backend
        run: |
          curl -X POST https://humidly-unsymbolic-jacquie.ngrok-free.dev/build/${{ inputs.build_id }}/complete \
          -H "Content-Type: application/json" \
          -d '{"artifact_url":"BUILD_SUCCESS"}'